/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniinventario;

import Panels.Contratar;
import Panels.Cuenta;
import Panels.Stock;
import Panels.verPersonal;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author flavio
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("MiniK");
        
        //iniciacion por defecto:
        CambiarPanel(btnCuenta, btnContratar, btnStock, btnVerPersonal);
        Cuenta p1=new Cuenta();
        int anch=PanelPrincipal.getWidth();
        int alt=PanelPrincipal.getHeight();
        p1.setSize(anch-10, alt-10);  
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
    }
    
    private void setColorButtons(JPanel panel){
        panel.setBackground(new Color(184, 130 , 255));
    }
    
    private void resetColorButtons(JPanel panel1, JPanel panel2, JPanel panel3){
        panel1.setBackground(new Color(64, 46, 89)); // [64,46,89]
        panel2.setBackground(new Color(64, 46, 89)); // [64,46,89]
        panel3.setBackground(new Color(64, 46, 89)); // [64,46,89]
    }
    
    private void CambiarPanel(JPanel panel1, JPanel panel2, JPanel panel3, JPanel panel4){
        setColorButtons(panel1);
        resetColorButtons(panel2, panel3, panel4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btnContratar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVerPersonal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStock = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCuenta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(46, 33, 64));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContratar.setBackground(new java.awt.Color(64, 46, 89));
        btnContratar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnContratarMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-añadir-usuario-masculino-30.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Contrata personal");

        javax.swing.GroupLayout btnContratarLayout = new javax.swing.GroupLayout(btnContratar);
        btnContratar.setLayout(btnContratarLayout);
        btnContratarLayout.setHorizontalGroup(
            btnContratarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContratarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnContratarLayout.setVerticalGroup(
            btnContratarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnContratarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(btnContratarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btnContratar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, 70));

        btnVerPersonal.setBackground(new java.awt.Color(64, 46, 89));
        btnVerPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVerPersonalMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-grupos-de-usuarios-filled-50.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ver personal");

        javax.swing.GroupLayout btnVerPersonalLayout = new javax.swing.GroupLayout(btnVerPersonal);
        btnVerPersonal.setLayout(btnVerPersonalLayout);
        btnVerPersonalLayout.setHorizontalGroup(
            btnVerPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVerPersonalLayout.setVerticalGroup(
            btnVerPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVerPersonalLayout.createSequentialGroup()
                .addGroup(btnVerPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVerPersonalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(btnVerPersonalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        sidepane.add(btnVerPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 70));

        btnStock.setBackground(new java.awt.Color(64, 46, 89));
        btnStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStockMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-análisis-de-stock-30.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Ver Stock");

        javax.swing.GroupLayout btnStockLayout = new javax.swing.GroupLayout(btnStock);
        btnStock.setLayout(btnStockLayout);
        btnStockLayout.setHorizontalGroup(
            btnStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnStockLayout.setVerticalGroup(
            btnStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStockLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(btnStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 70));

        btnCuenta.setBackground(new java.awt.Color(64, 46, 89));
        btnCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCuentaMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-automático-30.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cuenta");

        javax.swing.GroupLayout btnCuentaLayout = new javax.swing.GroupLayout(btnCuenta);
        btnCuenta.setLayout(btnCuentaLayout);
        btnCuentaLayout.setHorizontalGroup(
            btnCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCuentaLayout.setVerticalGroup(
            btnCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCuentaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(btnCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepane.add(btnCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 70));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 232, 527));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        bg.add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 0, 780, 471));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-medio-48.png"))); // NOI18N
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 477, 56, 50));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Empresa... empresa@myEmail.com");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 500, 574, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratarMousePressed
        // Contratar Personal
        CambiarPanel(btnContratar, btnCuenta, btnStock, btnVerPersonal);
        Contratar p1=new Contratar();
        int anch=PanelPrincipal.getWidth();
        int alt=PanelPrincipal.getHeight();
        p1.setSize(anch-10, alt-10);  
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
    }//GEN-LAST:event_btnContratarMousePressed

    private void btnVerPersonalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerPersonalMousePressed
        // Ver Personal
        CambiarPanel(btnVerPersonal, btnContratar, btnCuenta, btnStock);
        verPersonal p1=new verPersonal();
        int anch=PanelPrincipal.getWidth();
        int alt=PanelPrincipal.getHeight();
        p1.setSize(anch-10, alt-10);  
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_btnVerPersonalMousePressed

    private void btnStockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMousePressed
        // Ver stock
        CambiarPanel(btnStock, btnContratar, btnCuenta, btnVerPersonal);
        Stock p1=new Stock();
        int anch=PanelPrincipal.getWidth();
        int alt=PanelPrincipal.getHeight();
        p1.setSize(anch-10, alt-10);  
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_btnStockMousePressed

    private void btnCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuentaMousePressed
        // Informacion de usuario:
        CambiarPanel(btnCuenta, btnContratar, btnStock, btnVerPersonal);

        Cuenta p1=new Cuenta();
        int anch=PanelPrincipal.getWidth();
        int alt=PanelPrincipal.getHeight();
        p1.setSize(anch-10, alt-10);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_btnCuentaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnContratar;
    private javax.swing.JPanel btnCuenta;
    private javax.swing.JPanel btnStock;
    private javax.swing.JPanel btnVerPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
